defaults:
  - grpo_config
  - _self_
env:
  name: cvrp
  registered_version: CVRP-v1

  network:
    transformer_num_blocks: 2
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [ 512 ]
    mean_nodes_in_query: True

  training:
    num_epochs: 1000
    num_learner_steps_per_epoch: 500
    n_steps: 20
    total_batch_size: 32

  evaluation:
    eval_total_batch_size: 10000
    greedy_eval_total_batch_size: 10000

  a2c:
    normalize_advantage: False
    discount_factor: 1.0
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.005
    learning_rate: 1e-4

seed: 0
logger:
  type: "tensorboard"  # 指定日志记录器的类型为 tensorboard
  project: "grpo4co"
  name: "cvrp"
  save_checkpoint: true