# agent: "grpo"
#agent: "a2c"
agent: "ppo"
# agent: "dhvl"
grpo:
  supervision_mode: "outcome"
#  supervision_mode: "process"
#   supervision_mode: "ppo"
  clip_eps: 0.10
  normalize_adv: true
  kl_coef: 0.005
  percentile_p: -1
  mean_reward_method: true
  reward_mode: "sparse"

ppo:
  lambda: 0.95
  normalize_adv: True
  clip_eps: 0.10

dhvl:
  bootstrapping_factor: 1.90
  policy_delay: 2
  update_epochs: 4
  tau: 0.5
  clip_eps: 0.1
  minibatch_size: 64
  target_kl: 0.2
  tar_tau: 0.01