defaults:
  - grpo_config
  - _self_
env:
  name: knapsack
  registered_version: Knapsack-v1

  network:
    transformer_num_blocks: 6
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [ 512 ]

  training:
    num_epochs: 100
    num_learner_steps_per_epoch: 40
    n_steps: 100
    total_batch_size: 8

  evaluation:
    eval_total_batch_size: 10000
    greedy_eval_total_batch_size: 10000

  a2c:
    normalize_advantage: False
    discount_factor: 1.0
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 1e-4
seed: 0
logger:
  type: "tensorboard"  # 指定日志记录器的类型为 tensorboard
  project: "grpo4co"
  name: "knapsack"
  save_checkpoint: true