defaults:
  - grpo_config
  - _self_
env:
  name: minesweeper
  registered_version: Minesweeper-v0

  network:
    board_embed_dim: 4
    board_conv_channels: [ 8, 8, 8 ]
    board_kernel_shape: 3
    num_mines_embed_dim: 4
    final_layer_dims: [ 32, 32 ]

  training:
    num_epochs: 100
    num_learner_steps_per_epoch: 200
    n_steps: 128
    total_batch_size: 10

  evaluation:
    eval_total_batch_size: 5000
    greedy_eval_total_batch_size: 5000

  a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 3e-4

seed: 0
logger:
  type: "tensorboard"  # 指定日志记录器的类型为 tensorboard
  project: "grpo4co"
  name: "minesweeper"
  save_checkpoint: true