defaults:
  - grpo_config
  - _self_
env:
  name: sliding_tile_puzzle
  registered_version: SlidingTilePuzzle-v0

  network:
    num_channels: 32
    policy_layers: [ 128, 128 ]
    value_layers: [ 256, 256 ]

  training:
    num_epochs: 400
    num_learner_steps_per_epoch: 100
    n_steps: 960
    total_batch_size: 8

  evaluation:
    eval_total_batch_size: 512
    greedy_eval_total_batch_size: 512

  a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 2e-4

seed: 0
logger:
  type: "tensorboard"  # 指定日志记录器的类型为 tensorboard
  project: "grpo4co"
  name: "sliding_tile_puzzle"
  save_checkpoint: true